version: '3.8'

networks:
  proxy:
    external:
      name: app-network

services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio
    restart: always
    networks:
      - proxy
    ports:
      - "8081:8081"
    volumes:
      - ./:/usr/share/nginx/html
