export const SITE = {
    name: "Irwansyah Tools",
    title: "Irwansyah Tools - Viral Content Tools, Twibbon, QR, PDF, DNS, MX, SPF, DKIM",
    description:
        "Koleksi tools gratis: caption generator, caption plus hashtag generator, paraphraser, title headline generator, emoji text style, ucapan otomatis hari besar, template poster Ramadhan Idul Fitri Natal Tahun Baru, QR generator, QR and link tools, twibbon maker, image compress, image to PDF, PDF to image, PDF compress, image to ASCII, DNS lookup, DNS propagation checker, MX/A/NS/CNAME/TXT/CAA/SRV checker, SPF checker, DKIM checker, DKIM generator, DMARC checker, JSON formatter validator, regex tester, JWT decoder, UUID generator, timestamp converter, Base64, URL encode/decode, HTML encode/decode, AES encrypt/decrypt, hash generator.",
    url: "https://tools.irwansyah.my.id",
    locale: "id_ID",
    twitter: "@mirwansyahs"
};

export const NAV_ITEMS = [
    { label: "Caption Generator", href: "/tools/caption-generator" },
    { label: "Caption + Hashtag", href: "/tools/caption-hashtag-generator" },
    { label: "Paraphraser", href: "/tools/paraphraser" },
    { label: "Headline Generator", href: "/tools/headline-generator" },
    { label: "Emoji/Text Style", href: "/tools/emoji-text-style" },
    { label: "Ucapan Hari Besar", href: "/tools/holiday-greeting-generator" },
    { label: "Poster Hari Besar", href: "/tools/holiday-poster-maker" },
    { label: "QR Generator", href: "/tools/qr-generator" },
    { label: "QR/Link Tools", href: "/tools/qr-link-tools" },
    { label: "Twibbon Maker", href: "/tools/twibbon-maker" },
    { label: "Image Compress", href: "/tools/image-compress" },
    { label: "Image to PDF", href: "/tools/image-to-pdf" },
    { label: "PDF to Image", href: "/tools/pdf-to-image" },
    { label: "PDF Compress", href: "/tools/pdf-compress" },
    { label: "Image to ASCII", href: "/tools/image-to-ascii" },
    { label: "DNS Propagation", href: "/tools/dns-propagation" },
    { label: "DNS Lookup", href: "/tools/dns-lookup" },
    { label: "MX Lookup", href: "/tools/mx-lookup" },
    { label: "A Lookup", href: "/tools/a-lookup" },
    { label: "CAA Checker", href: "/tools/caa-checker" },
    { label: "SRV Checker", href: "/tools/srv-checker" },
    { label: "CNAME Lookup", href: "/tools/cname-lookup" },
    { label: "TXT Lookup", href: "/tools/txt-lookup" },
    { label: "NS Lookup", href: "/tools/ns-lookup" },
    { label: "SPF Checker", href: "/tools/spf-checker" },
    { label: "DKIM Checker", href: "/tools/dkim-checker" },
    { label: "DKIM Generator", href: "/tools/dkim-generator" },
    { label: "DMARC Checker", href: "/tools/dmarc-checker" },
    { label: "JSON Formatter/Validator", href: "/tools/json-formatter-validator" },
    { label: "JSON Viewer", href: "/tools/json-viewer" },
    { label: "Regex Tester", href: "/tools/regex-tester" },
    { label: "JWT Decoder", href: "/tools/jwt-decoder" },
    { label: "Timestamp Converter", href: "/tools/timestamp-converter" },
    { label: "UUID Generator", href: "/tools/uuid-generator" },
    { label: "HTML Encode/Decode", href: "/tools/html-encode-decode" },
    { label: "Base64 Encode/Decode", href: "/tools/base64-encode-decode" },
    { label: "URL Encode/Decode", href: "/tools/url-encode-decode" },
    { label: "Base64 to Image", href: "/tools/base64-to-image" },
    { label: "AES Encrypt/Decrypt", href: "/tools/aes-encrypt-decrypt" },
    { label: "Hash Generator", href: "/tools/hash-generator" }
];
